"""rename files field

Revision ID: 041a579da47d
Revises: 9fb52267564b
Create Date: 2024-11-22 23:59:39.779467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '041a579da47d'
down_revision: Union[str, None] = '9fb52267564b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('new_file_name', sa.String(length=122), nullable=True))
    op.drop_column('files', 'path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('path', mysql.VARCHAR(length=122), nullable=True))
    op.drop_column('files', 'new_file_name')
    # ### end Alembic commands ###
