"""add unqiue constraint

Revision ID: 3c1f71103e6d
Revises: 041a579da47d
Create Date: 2024-11-24 19:05:38.366079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c1f71103e6d'
down_revision: Union[str, None] = '041a579da47d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_file', 'allowed_user_files', ['user_id', 'allowed_file_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_file', 'allowed_user_files', type_='unique')
    # ### end Alembic commands ###
