"""add files app

Revision ID: 9fb52267564b
Revises: 8402be3a8dd8
Create Date: 2024-11-22 21:37:16.569444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fb52267564b'
down_revision: Union[str, None] = '8402be3a8dd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('path', sa.String(length=122), nullable=True),
    sa.Column('downloaded', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    op.create_table('allowed_user_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('allowed_file_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['allowed_file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allowed_user_files_id'), 'allowed_user_files', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_allowed_user_files_id'), table_name='allowed_user_files')
    op.drop_table('allowed_user_files')
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
